### ISSUE TITLE
Attach manuscript/TPEN project/TPEN lines to Named Gloss

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/Glossing-Matthew#16]
What is the workflow for this?  This layout page will need to know the named Gloss URI and the TPEN project URI (or ensure this page has a UI to gather those things before continuing).

**Comment by cubap** [comment]
* gloss buttons (or whatever element holds them) will know of the URI of each line on the page associated with it;
* each line has a `data-gloss-uri` that matches the `@id` of a named Gloss;
* Named Gloss = AnnotationCollection
* Each folio transcription has [lines] annotations in AnnotationPages that are collected by each Named Gloss

**NB** AnnoCollections work more "RDFy" than lists, so we SHOULD to create a "first" "last" (but I won't).

```json
// Gloss 1 (RERUM has some optional '@' issues)
{ "@context": "http://iiif.io/api/presentation/3/context.json",
  "@id": "http://store.rerum.io/...G1",
  "type": "AnnotationCollection",
  "label": "Gloss 1",
... "chapter", "verse", "description" ...
}

//  on Canvas C1, for each Gloss
{ "@context": "http://iiif.io/api/presentation/3/context.json",
  "@id": "http://store.rerum.io/...A1",
  "@type": "AnnotationPage",
  "partOf": {
    "id": "http://store.rerum.io/...G1",
    "type": "AnnotationCollection"
  },
  "items": [ "line1", "line2", "line3", ...  ]
}

// Annotations on the lines
{ "@context": "http://www.w3.org/ns/anno.jsonld",
  "@id": "http://store.rerum.io/...L1",
  "@type": "Annotation",
  "body": "http://t-pen.org/TPEN/line/001",
  "target": "http://store.rerum.io/...G1",
  "motivation": "linking"
}
```

**Comment by cubap** [comment]
No, this isn't quite right. The target of the annotation should be the Gloss, but the Gloss shouldn't then collect them all if we've reified it separately. Can we do this without an `AnnotationCollection`? The Gloss can just be a Gloss.
